### ISSUE TITLE
Configuração

### ISSUE THREAD

**Issue by ricardodarocha** [dliocode/horse-query#1]
Eu baixei o repositório https://github.com/viniciussanchez/dataset-serialize e configurei no library path todos os sources mas ao compilar o projeto com horse-query dá os erros
```
[dcc32 Error] Horse.Query.pas(19): E2003 Undeclared identifier: 'TCaseNameDefinition'
[dcc32 Error] Horse.Query.pas(27): E2003 Undeclared identifier: 'TDataSetSerializeConfig'
```
consegue me ajudar?

**Comment by dliocode** [comment]
Oi.. Você tentou instalar com o Boss?

**Comment by ricardodarocha** [comment]
Consegui resolver

Eu reinstalei todo o pacote dataset-serialize (excluí a pasta e instalei de novo)
Mesmo com o Boss tinha dado erro, mas agora ficou show de bola, parabéns

**Comment by dliocode** [comment]
Perfeito.. Qualquer coisa avisa.. Estou no grupo do Boss no Telegram, qualquer coisa só chamar lá..
